# this specifies the folder where the data is stored
# as outlined in the README, this should be the default configuration
# for mounting Rice RDF on your machine
datadir:
  osx: "/Volumes/research/jd82/"
  linux: "/home/jd82/RDF/jd82/"
  windows: "Z:/jd82/"
