# this environment file will let you
# 1) run the code to generate and update the datasets
# 2) do basic exploration of the data
# a future task could separate into a core and exploration environment, but this is low priority
name: climatedata
channels:
  - conda-forge # the best place for community developed package
  - bioconda # needed for snakemake
  - defaults # backup
dependencies:
  - python>=3.11
  - black # clean code and make it pretty
  - cfgrib # read grib files
  - dask # parallel processing
  - ipython # for interactive exploring
  - jupyter # for notebooks
  - matplotlib # core visualizations
  - mypy # type checking
  - netcdf4 # read netcdf files
  - pandas # dataframes and datetime
  - pylint # catch errors before you make them
  - snakefmt # format snakefiles correctly
  - snakemake # workflow management engine
  - xarray # for all gridded climate data
  - pip # install local packages
  - pip:
      - -e ./nexrad
