name: nexrad
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.7 # specify python version
  - black # clean code and make it pretty
  - cartopy # mapping
  - dask # Parallel processing library
  - ipykernel # to run locally
  - jupyter # to run notebooks
  - mamba>=0.22.1 # better solver
  - matplotlib # mapping
  - mypy # type checking
  - netcdf4 # Wrapper for netcdf4
  - numpy # N-d array and numerics
  - pandas # Labeled array library
  - pylint # catch errors before you make them
  - snakemake
  - snakefmt
  - xarray # N-d labeled array library
