name: climatedata
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10 # specify python version
  - black # clean code and make it pretty
  - ipykernel # for playing around locally
  - mypy # type checking
  - pylint # catch errors before you make them
  - snakemake # workflow management engine
  - snakefmt # format snakefiles correctly
  - xarray # N-d labeled array library
  - pip # install local packages
  - pip:
      - -e .
