# some parameters to control the ERA5 reanalysis data
era5:
  lonmin: -125
  lonmax: -65
  latmin: 25
  latmax: 50
  resolution: 0.25
  first_year: 2015
  last_year: 2022
  vars:
    pressure_level:
        - u_component_of_wind
        - v_component_of_wind
    single_level:
      - vertical_integral_of_eastward_water_vapour_flux
      - vertical_integral_of_northward_water_vapour_flux
      - 2m_temperature
